/* eslint-disable */

export const stockList = [
    { name: 'Apple', symbol: 'AAPL' },
    { name: 'Google', symbol: 'GOOGL' },
    { name: 'Microsoft', symbol: 'MSFT' },
    { name: 'Amazon', symbol: 'AMZN' },
    { name: 'Tesla', symbol: 'TSLA' },
    { name: 'Facebook', symbol: 'META' },
    { name: 'NVIDIA', symbol: 'NVDA' },
    { name: 'Netflix', symbol: 'NFLX' },
    { name: 'Adobe', symbol: 'ADBE' },
    { name: 'Intel', symbol: 'INTC' },
    { name: 'Cisco', symbol: 'CSCO' },
    { name: 'Oracle', symbol: 'ORCL' },
    { name: 'IBM', symbol: 'IBM' },
    { name: 'Salesforce', symbol: 'CRM' },
    { name: 'PayPal', symbol: 'PYPL' },
    { name: 'Square', symbol: 'SQ' },
    { name: 'Shopify', symbol: 'SHOP' },
    { name: 'Zoom', symbol: 'ZM' },
    { name: 'Spotify', symbol: 'SPOT' },
    { name: 'Snap', symbol: 'SNAP' },
    { name: 'Twitter', symbol: 'TWTR' },
    { name: 'Uber', symbol: 'UBER' },
    { name: 'Lyft', symbol: 'LYFT' },
    { name: 'Pinterest', symbol: 'PINS' },
    { name: 'eBay', symbol: 'EBAY' },
    { name: 'Alibaba', symbol: 'BABA' },
    { name: 'Baidu', symbol: 'BIDU' },
    { name: 'JD.com', symbol: 'JD' },
    { name: 'Tencent', symbol: 'TCEHY' },
    { name: 'Samsung', symbol: 'SSNLF' },
    { name: 'Sony', symbol: 'SONY' },
    { name: 'LG', symbol: 'LPL' },
    { name: 'Qualcomm', symbol: 'QCOM' },
    { name: 'AMD', symbol: 'AMD' },
    { name: 'Micron', symbol: 'MU' },
    { name: 'Texas Instruments', symbol: 'TXN' },
    { name: 'Broadcom', symbol: 'AVGO' },
    { name: 'AT&T', symbol: 'T' },
    { name: 'Verizon', symbol: 'VZ' },
    { name: 'T-Mobile', symbol: 'TMUS' },
    { name: 'Disney', symbol: 'DIS' },
    { name: 'Coca-Cola', symbol: 'KO' },
    { name: 'PepsiCo', symbol: 'PEP' },
    { name: 'McDonald\'s', symbol: 'MCD' },
    { name: 'Starbucks', symbol: 'SBUX' },
    { name: 'Walmart', symbol: 'WMT' },
    { name: 'Target', symbol: 'TGT' },
    { name: 'Costco', symbol: 'COST' },
    { name: 'Home Depot', symbol: 'HD' },
    { name: 'Lowe\'s', symbol: 'LOW' }
];

globalThis.stockList = stockList; // Attach to global object
